# Generated by Django 5.2.5 on 2025-08-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrmeblogapp', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='heroimage',
            options={'ordering': ['order', 'created_at']},
        ),
        migrations.AddField(
            model_name='heroimage',
            name='order',
            field=models.PositiveIntegerField(default=0, help_text='Order of display in slider (lower numbers appear first)'),
        ),
    ]
