# Generated by Django 5.2.5 on 2025-08-24 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrmeblogapp', '0002_alter_heroimage_options_heroimage_order'),
    ]

    operations = [
        migrations.CreateModel(
            name='PageHeroImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('page', models.CharField(choices=[('categories', 'Categories Page'), ('destination', 'Destination Page'), ('about', 'About Page'), ('contact', 'Contact Page')], max_length=20, unique=True)),
                ('image', models.FileField(upload_to='page_hero/')),
                ('title', models.CharField(blank=True, max_length=200)),
                ('subtitle', models.CharField(blank=True, max_length=300)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'ordering': ['page'],
            },
        ),
    ]
