# Generated by Django 5.2.5 on 2025-08-29 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrmeblogapp', '0004_postlink'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='show_in_footer',
            field=models.BooleanField(default=False, help_text='Show this category in the site footer'),
        ),
    ]
