# Generated by Django 5.2.5 on 2025-09-05 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrmeblogapp', '0005_category_show_in_footer'),
    ]

    operations = [
        migrations.AddField(
            model_name='destination',
            name='hero_image',
            field=models.FileField(blank=True, null=True, upload_to='destinations/hero/'),
        ),
        migrations.AddField(
            model_name='destination',
            name='mini_video',
            field=models.FileField(blank=True, null=True, upload_to='destinations/video/'),
        ),
    ]
