# Generated by Django 5.2.5 on 2025-09-05 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('zikrmeblogapp', '0006_destination_hero_image_destination_mini_video'),
    ]

    operations = [
        migrations.CreateModel(
            name='HomeMiniVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('video_file', models.FileField(blank=True, help_text='Upload a video file', null=True, upload_to='home/video/')),
                ('youtube_url', models.URLField(blank=True, help_text='Or provide a YouTube URL')),
                ('is_active', models.BooleanField(default=True)),
                ('autoplay', models.BooleanField(default=True, help_text='Auto-play the video')),
                ('muted', models.BooleanField(default=True, help_text='Start video muted')),
            ],
            options={
                'verbose_name': 'Home Mini Video',
                'verbose_name_plural': 'Home Mini Videos',
            },
        ),
    ]
